/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BugsLife;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;

/**
 *
 * @author user
 */
public class MonthlyReport extends javax.swing.JFrame {

    /**
     * Creates new form MonthlyReportDashboard
     */
    private String issueChoice;
    private int maxTag;
    private String maxTagname;
    private String chartOption;
    private String statuschartOption;
    private int issueResolved, issueUnresolved, issueinProgress;
    private int issue1, issue2, issue3, issue4, issue5;
    private int issueResolved1, issueResolved2, issueResolved3, issueResolved4, issueResolved5, issueUnresolved1, issueUnresolved2, issueUnresolved3, issueUnresolved4, issueUnresolved5, issueinProgress1, issueinProgress2, issueinProgress3, issueinProgress4, issueinProgress5;
    private int maxscore = 0;
    private String maxname = "";
    private ArrayList<String> maxscorenamelist = new ArrayList();
    private String month;
    private String[][] arrTag;
    private IssuesDAO iss;
    private UsersDAO user;
    private ArrayList<User> usslist;
    private ArrayList<Issue> isslist;
    private ArrayList<Issue> issueofsamemonth = new ArrayList();

    public MonthlyReport() {
        initComponents();
    }

    MonthlyReport(int year, String month, int projectIndex) throws SQLException {
        //initialise userDAO
        this.user = new UsersDAO();
        //pass all user list from database into Java ArrayList
        usslist = user.getAllUsers();
        //get month from previous class
        this.month = month;
        //initialise IssuesDAO
        iss = new IssuesDAO();
        //get all issue of certain project ID from database and pass into Java ArrayList
        isslist = iss.getAllIssue(projectIndex + 1);
        //loop through the issuelist
        for (int i = 0; i < isslist.size(); i++) {
            //get timestamp of current issue
            long issueTimeStamp = isslist.get(i).getTimestamp();
            //convert timestamp into Date
            Date date1 = new Date(issueTimeStamp * 1000L);
            //convert Date into LocalDate
            LocalDate date = date1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            //if current issue created year is same as the year choose from the jtree
            if (date.getYear() == year) {
                //if current issue created month is same as the year choose from the jtree
                if (date.getMonth().toString().equalsIgnoreCase(this.month)) {
                    //add into ArrayList of issue of same month
                    issueofsamemonth.add(isslist.get(i));
                }
            }
        }
        //call method generateReport() to determine value of all details needed to be displayed
        generatereport();
        //initialise components of the GUI
        initComponents();
        this.setLocationRelativeTo(null);
        //if there are no issue in this month, notify user
        if (issueofsamemonth.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nothing happened this month", "Empty Month", JOptionPane.PLAIN_MESSAGE);
            this.dispose();
        } else {
            this.setVisible(true);
        }

        this.setDefaultCloseOperation(HIDE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText(month+" Report");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel2.setText("Star User of The Month: "+maxname);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Number of Issues This Month: "+issueofsamemonth.size());

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel12.setText("Generate Issue Graph Here");

        jComboBox3.setBackground(new java.awt.Color(153, 204, 255));
        jComboBox3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bar Chart","Pie Chart","Line Graph" }));
        jComboBox3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Generate Graph");
        jButton3.setToolTipText("");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel5.setText("Issues In Progress: "+issueinProgress);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel6.setText("Issue Unresolved: "+issueUnresolved);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel7.setText("Issues Resolved: "+issueResolved);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel8.setText("Generate Status Graph Here");

        jComboBox2.setBackground(new java.awt.Color(153, 204, 255));
        jComboBox2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bar Chart","Pie Chart","Line Graph" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Generate Graph");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel10.setText("Most Common Tag of the Week:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel4.setText("Generate Tag Graph Here");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel9.setText("Tag Name: "+maxTagname);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel11.setText("Tag Numbers: "+maxTag);

        jComboBox1.setBackground(new java.awt.Color(153, 204, 255));
        jComboBox1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bar Chart","Pie Chart","Line Graph" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Generate Graph");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel13.setText("Monthly Report");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //method to retrive choice of issue chart from user
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        issueChoice = jComboBox3.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox3ActionPerformed
    //method to detect mouse click and generate issue chart based on user choice
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //if bar chart is choosen, display data in bar chart
        if (issueChoice.equalsIgnoreCase("Bar Chart")) {
            new DisplayBar(issue1, issue2, issue3, issue4, issue5);
        } //if pie chart is choosen, display data in pie chart
        else if (issueChoice.equalsIgnoreCase("Pie Chart")) {
            new DisplayPie(issue1, issue2, issue3, issue4, issue5);
        } //if line graph is choosen, display data in line graph
        else if (issueChoice.equalsIgnoreCase("Line Graph")) {
            new DisplayLine(issue1, issue2, issue3, issue4, issue5);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    //method to retrive choice of status chart from user
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        statuschartOption = jComboBox2.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox2ActionPerformed
    //method to detect mouse click and generate status chart based on user choice
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //if bar chart is choosen, display data in bar chart
        if (statuschartOption.equalsIgnoreCase("Bar Chart")) {
            new DisplayBar(issueinProgress, issueResolved, issueUnresolved);
        } //if pie chart is choosen, display data in pie chart
        else if (statuschartOption.equalsIgnoreCase("Pie Chart")) {
            new DisplayPie(issueinProgress, issueResolved, issueUnresolved);
        } //if line graph is choosen, display data in line graph
        else if (statuschartOption.equalsIgnoreCase("Line Graph")) {
            new DisplayLine(issueResolved1, issueResolved2, issueResolved3, issueResolved4, issueResolved5, issueUnresolved1, issueUnresolved2, issueUnresolved3, issueUnresolved4, issueUnresolved5, issueinProgress1, issueinProgress2, issueinProgress3, issueinProgress4, issueinProgress5);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    //method to retrive choice of tag chart from user
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        chartOption = jComboBox1.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox1ActionPerformed
    //method to detect mouse click and generate tag chart based on user choice
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //if bar chart is choosen, display data in bar chart
        if (chartOption.equalsIgnoreCase("Bar Chart")) {
            new DisplayBar(arrTag);
        } //if pie chart is choosen, display data in pie chart
        else if (chartOption.equalsIgnoreCase("Pie Chart")) {
            new DisplayPie(arrTag);
        } //if line graph is choosen, display data in line graph
        else if (chartOption.equalsIgnoreCase("Line Graph")) {
            new DisplayLine(arrTag);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthlyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthlyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthlyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthlyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonthlyReport().setVisible(true);
            }
        });
    }

    private void generatereport() {
        //get top scorer
        //**********************************************************************************************************************************************************
        //loop through the user ArrayList
        for (int i = 0; i < usslist.size(); i++) {
            //if user's point is higher than maxscore
            if (usslist.get(i).getPoints() > maxscore) {
                //clear the max score list
                maxscorenamelist.clear();
                //add the maxscore user into the max score list
                maxscorenamelist.add(usslist.get(i).getUsername());
                //update max score to the maxscore user's point
                maxscore = usslist.get(i).getPoints();
            } //if user's point is equal to max score, means multiple winners exist
            else if (usslist.get(i).getPoints() == maxscore) {
                //add the user into the maxscorelist
                maxscorenamelist.add(usslist.get(i).getUsername());
            }
        }
        //set the maxscorename into a string to be displayed
        for (int i = 0; i < maxscorenamelist.size(); i++) {
            maxname += maxscorenamelist.get(i) + ", ";
        }
        //get Tag Count
        //**********************************************************************************************************************************************************
        //initialise a ArrayList to store tag
        ArrayList<String> list = new ArrayList();
        for (int i = 0; i < issueofsamemonth.size(); i++) {
            //loop through each issue's tag Arraylist
            for (int j = 0; j < issueofsamemonth.get(i).getTag().size(); j++) {
                //if the tag of current issue is not in the list
                if (!list.contains(issueofsamemonth.get(i).getTag().get(j))) {
                    //if the tag is null
                    if (issueofsamemonth.get(i).getTag().get(j).equalsIgnoreCase("")) {
                        //add as untag
                        if (!list.contains("Untag")) {
                            list.add("Untag");
                        }
                    } else {
                        //add into the list
                        list.add(issueofsamemonth.get(i).getTag().get(j));
                    }
                }
            }
        }
        //initialise a 2D array to differentiate count and tag name
        arrTag = new String[list.size()][2];
        //loop throught the 2D arary
        for (int i = 0; i < arrTag.length; i++) {
            //add the tag from ArrayList into the 2D array and and initialise tag count as 0
            arrTag[i][0] = list.get(i);
            arrTag[i][1] = "0";
        }

        //loop through list with issue of same day 
        for (int i = 0; i < issueofsamemonth.size(); i++) {
            //loop through tag of current issue
            for (int j = 0; j < issueofsamemonth.get(i).getTag().size(); j++) {
                //loop the 2D array
                for (int k = 0; k < arrTag.length; k++) {
                    if (issueofsamemonth.get(i).getTag().get(j).equalsIgnoreCase("") && arrTag[k][0].equalsIgnoreCase("Untag")) {
                        int count = Integer.parseInt(arrTag[k][1]);
                        count++;
                        arrTag[k][1] = Integer.toString(count);
                    } //if the tag of 2D array is found in the current issue tag
                    else if (issueofsamemonth.get(i).getTag().get(j).equalsIgnoreCase(arrTag[k][0])) {
                        //increase the count of tag insdie 2D array by one
                        int count = Integer.parseInt(arrTag[k][1]);
                        count++;
                        arrTag[k][1] = Integer.toString(count);
                    }
                }
            }
        }
        //determine the tag that appears the most 
        //**********************************************************************************************************************************************************
        //loop through the 2D array
        for (int i = 0; i < arrTag.length; i++) {
            //if count of current tag> max tag, replace it
            if (Integer.parseInt(arrTag[i][1]) > maxTag) {
                maxTagname = arrTag[i][0];
                maxTag = Integer.parseInt(arrTag[i][1]);
            } //if there exist a tag of same ammount, stack it
            else if (Integer.parseInt(arrTag[i][1]) == maxTag) {
                maxTagname = maxTagname + " " + arrTag[i][0];
            }
        }
        //determine the count of status for each week
        //**********************************************************************************************************************************************************
        //loop all the issue in the same month
        for (int i = 0; i < issueofsamemonth.size(); i++) {
            //get timestamp
            long timestamp = issueofsamemonth.get(i).getTimestamp();
            //conver timestamp into Date
            Date date = new Date(timestamp * 1000L);
            //convert Date into LocalDate
            LocalDate ld = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            //if current issue's day is between 1 to 7
            if (ld.getDayOfMonth() >= 1 && ld.getDayOfMonth() <= 7) {
                //issueofweek1++
                issue1++;
                //if status of that issue is closed, issueresolved of week1++
                if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("Closed")) {
                    issueResolved1++;
                } //if status of that issue is open, issueunresolved of week 1++
                else if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("Open")) {
                    issueUnresolved1++;
                } //if status of that issue is inprogress, issueinprogress of week1++
                else if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("In Progress")) {
                    issueinProgress1++;
                }
            } //if current issues's day is between 8 - 14
            else if (ld.getDayOfMonth() >= 8 && ld.getDayOfMonth() <= 14) {
                //issueofweek2++
                issue2++;
                //if status of that issue is closed, issueresolved of week2++
                if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("Closed")) {
                    issueResolved2++;
                } //if status of that issue is copen, issueunresolved of week2++
                else if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("Open")) {
                    issueUnresolved2++;
                } //if status of that issue is in progress, issueinprogress of week2++
                else if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("In Progress")) {
                    issueinProgress2++;
                }
            } //if current issues's day is between 15 - 21
            else if (ld.getDayOfMonth() >= 15 && ld.getDayOfMonth() <= 21) {
                //issueofweek3++
                issue3++;
                //if status of that issue is closed, issueresolved of week3++
                if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("Closed")) {
                    issueResolved3++;
                } //if status of that issue is open, issueunresolved of week3++
                else if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("Open")) {
                    issueUnresolved3++;
                } //if status of that issue is in progress, issueinprogress of week3++
                else if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("In Progress")) {
                    issueinProgress3++;
                }
            } //if current issues's day is between 22 - 28
            else if (ld.getDayOfMonth() >= 22 && ld.getDayOfMonth() <= 28) {
                //issueofweek4++
                issue4++;
                //if status of that issue is closed, issueresolved of week4++
                if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("Closed")) {
                    issueResolved4++;
                } //if status of that issue is open, issueunresolved of week4++
                else if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("Open")) {
                    issueUnresolved4++;
                } //if status of that issue is in progress, issueinprogress of week4++
                else if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("In Progress")) {
                    issueinProgress4++;
                }
            } //if current issues's day is between 29 - 31
            else if (ld.getDayOfMonth() >= 29 && ld.getDayOfMonth() <= 31) {
                //issueofweek5++
                issue5++;
                //if status of that issue is closed, issueresolved of week5++
                if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("Closed")) {
                    issueResolved5++;
                } //if status of that issue is open, issueunresolved of week5++
                else if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("Open")) {
                    issueUnresolved5++;
                } //if status of that issue is in progress, issueinprogress of week5++
                else if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("In Progress")) {
                    issueinProgress5++;
                }
            }
        }
        //get issue of each status(w/o considering week)
        //**********************************************************************************************************************************************************
        //loop the ArrayList of issue within the same month
        for (int i = 0; i < issueofsamemonth.size(); i++) {
            //if status of current issue is closed
            if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("Closed")) {
                //issueresolved ++
                issueResolved++;
            } //if satus of current issue is open
            else if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("Open")) {
                //issueunresolved++
                issueUnresolved++;
            } //if status of current issue is in progress
            else if (issueofsamemonth.get(i).getStatus().equalsIgnoreCase("In Progress")) {
                //issureinprogress++
                issueinProgress++;
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
